version: '3.4'

services:
  contosouniversity:
    image: ${DOCKER_REGISTRY-}contosouniversity
    build:
      context: .
      dockerfile: ContosoUniversity/Dockerfile
    depends_on:
      - sqldata
#    ports:
#      - "80:80"



  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
#    ports:
#      - "81:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=tvxs721#3
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
       - db-data:/var/lib/mysql/data
 


  webweb:
    image: ${DOCKER_REGISTRY-}webweb
    build:
      context: .
      dockerfile: WebWeb/Dockerfile

volumes:
  db-data:
